### ISSUE TITLE
Add Instagram module

### ISSUE THREAD

**Issue by DakotaNelson** [DakotaNelson/pushpin-web#10]
Pretty much what it says. The hangup right now is that Instagram seems to use some sort of weird OAuth flow where the user has to manually click a popup; since Docker hates everything, this might be a bit tricky.

**Comment by larssb** [comment]
So pushpin-web does not actually support Instagram yet? Installed the application and:

- Can't see the option to add a key to use with Instagram anywhere. Hmm, will support come?

And thank you for a great app.

**Comment by DakotaNelson** [comment]
Yep, here's what it says on the [Instagram API page](https://www.instagram.com/developer/) right now:

<img width="800" alt="2019-01-07 14_48_47-instagram developer documentation" src="https://user-images.githubusercontent.com/6242741/50797963-75f11a00-128b-11e9-9ff6-cac98450224d.png">

Basically, Instagram doesn't expose their data programatically as far as I know. (If I'm wrong, someone please let me know!)

Now that I think of it - this issue should be closed. Feel free to keep commenting but I'm gonna close this out.
