### ISSUE TITLE
Docker-Compose .yml error

### ISSUE THREAD

**Issue by Tu5k4rr** [DakotaNelson/pushpin-web#15]
"docker-compose up" doesn't recognise the DEBUG value "False" in the environment and celery parameters section in the .yml config for compose

In this file ; https://github.com/DakotaNelson/pushpin-web/blob/master/docker-compose.yml

I changed the 'False' value to 'null' and seems to be working fine. Not sure if this is a change in docker compose. but thought id mention it.

Thanks,

@Tu5k4rr

**Comment by DakotaNelson** [comment]
Thanks - this is good to know! I'll take a look at this as soon as I can free up some time.

**Comment by Fortesqueu** [comment]
Same for me here after changing all the "False" for null and running with sudo docker-compose

**Comment by DakotaNelson** [comment]
Any chance one of you is willing to open a PR with your changes? It would be much appreciated!

**Comment by Tu5k4rr** [comment]
I'll take a look this week unless. Fortesqueu beats me to it.

**Comment by DakotaNelson** [comment]
Thank you! I'll keep my eyes open for it.

**Comment by Tu5k4rr** [comment]
Sent Push request. Let me know if there is anything else you need.

**Comment by DakotaNelson** [comment]
Merged #16. Thank you, @Tu5k4rr!
